### PR TITLE
Add section on working with PRs as a reviewer

### PR DESCRIPTION
**Pull request by frivoal**
It's not just test authors that may be new to Git/Github. Reviewers should also get some help about how to deal with PR branches, how to clone them locally to review them, how do amend a Pull Request...

CCing @fantasai, since you requested this to be written down. @gsnedders can review this from the point of view of whether this is correct, and @fantasai can review from the point of view of whether this is ineligible by someone wanting to learn how to do that.

### CODE REVIEW

**Comment by gsnedders** [comment]
FWIW: github-101 is likely to be largely rewritten

**Comment by frivoal** [comment]
Does it sound like you could merge this in, and then refactor/re-write, or would you rather do your re-write first, and then consider this?

**Comment by gsnedders** [comment]
@frivoal this is one of the must-land pages for the docs rewrite, AIUI, given I believe it blocks the CSS WG moving to wpt

**Comment by frivoal** [comment]
@gsnedders I believe that the section I added to it in particular is in particularly high demand, since a few important people (Fantasai and Gerard Talbot) are more familiar with hg than git, and that part of the process may be the least obvious one.

**Pull request merged**
